### ISSUE TITLE
BX Slider wrong path

### ISSUE THREAD

**Issue by ierpe** [antongorodezkiy/pdf-light-viewer#3]
Hi,

I just installed the plugin from the WP repo, and I have JS error.

The plugin is looking for ``` .../plugins/pdf-light-viewer/assets/bower_components/bxslider-4/dist/jquery.bxslider.min.js  ``` and ``` .../plugins/pdf-light-viewer/assets/bower_components/bxslider-4/dist/jquery.bxslider.css ```

but in fact there is no ``` dist ``` folder in the assets folder.
Removing ``` dist ``` in the ```.../plugins/pdf-light-viewer/controllers/AssetsController.php ``` file solved it for me.

If you want I can fork and make a pull request, but for such a small change... :) Let me know

**Comment by antongorodezkiy** [comment]
Hi @ierpe,

Thank you.
Strange. Probably some issue with updating assets. There is dist folder in the latest bxslider https://github.com/stevenwanderski/bxslider-4 and I have it too on the demo site http://pdf-light-viewer.wp.teamlead.pw/demo/

Anyway, thank you for reporting, will check this. There is no need for PR so far, I believe the issue somewhere else.

**Comment by ierpe** [comment]
Hi, thanks for your answer.
I am using the WordPress Bedrock stack. which deals with plugins using composer, so maybe the problem comes from there ... ?

**Comment by zipzit** [comment]
Ha. I came here to report the same error / concern.

**Comment by zipzit** [comment]
This issue still not corrected.   In fact there are a whole lot of errors on the sample site you've shown.  The errors are easily visible in Chrome DevTools.   Are you sure you don't need a pull request?  (We're happy to help...)

**Comment by zipzit** [comment]
Hmm. I really hate seeing all those errors when I'm troubleshooting my pages.  Please be patient with me I'm still learning this stuff, including how Bower works.  When I go to my command line interpreter,

`$ bower search bxSlider
Search results:
    bxslider-4 git://github.com/wandoledzep/bxslider-4.git
    bxslider git://github.com/wandoledzep/bxslider.git
    bxSlider git://github.com/wandoledzep/bxslider-4.git
    bolster.bxSlider git://github.com/bolster/bxslider-4.git
    bxslider-4-kallisto git://github.com/kallisto-consulting/bxslider-4.git
    bxslider-4-jz-test git://github.com/jzelenkov/bxslider-4.git
    bxslider-4-jz git://github.com/jzelenkov/bxslider-4.git
    bx-slider.js git://github.com/stevenwanderski/bxslider-4.git
    massmans-bxslider git://github.com/massimans/bxslider-4.git
    dw-bxslider-4 git://github.com/stevenwanderski/bxslider-4.git`

Unfortunately, `bxslider-4` in bower == `git://github.com/wandoledzep/bxslider-4.git`
I can't even find that repository.  Instead, I think we want to use https://github.com/stevenwanderski/bxslider-4 which appears to have a bower 'code' of `dw-bxslider-4`

With that in mind, I'm thinking the file in this distribution, pdf-light-viewer/assets/bower.json needs a minor revision. 
`{
    "name": "pdf-light-viewer",
    "author": "E.Kozachek",
    "version": "1.0.0",              <-- update as required.
    "dependencies": {
        "jquery.lazyload": "latest",
        "fontawesome": "latest",
        "pure": "0.6.0",
        "bxslider-4": "latest",       <--   should this line should be:  "dw-bxslider-4": "latest"
        "jquery-zoom": "latest",
        "kayahr-jquery-fullscreen-plugin": "kayahr/jquery-fullscreen-plugin",
        "jquery-zoom": "latest"
    }
}`

Is this the right approach to fix all the errors I'm seeing?  Many thanks, Zip!

**Comment by antongorodezkiy** [comment]
@zipzit yes, you're right - seems I broke something with the latest release.

Also I believe the original repo from the author `https://github.com/stevenwanderski/bxslider-4/` would be the best solution.

**Comment by ierpe** [comment]
so... are you going to update the plugin with a fix?

**Comment by antongorodezkiy** [comment]
@ierpe already updated. Please check version 1.1.3 on [github](https://github.com/antongorodezkiy/pdf-light-viewer/releases/tag/v1.1.3) or on [wordpress](https://wordpress.org/plugins/pdf-light-viewer)
