### ISSUE TITLE
pdf-light-viewer template is not functional from user's theme.

### ISSUE THREAD

**Issue by zipzit** [antongorodezkiy/pdf-light-viewer#5]
I'm hoping to update the template a little bit.  I'd like to have both a desktop and mobile display.  (My intent was to have two div wrappers.. one in `display: block` mode, the other in `display: none` mode.  Flip flop 'em using `@media` calls...)  When in mobile mode, I'd just like to display simple images for each page,  all arranged in a column.  I was hoping to customize the template file, and try it first on my own (before making a recommendation to github.)

The instructions clearly say:

> Templates control
> You can create shortcode-pdf-light-viewer.php in your theme or copy it from templates folder to your theme folder to override all default plugin template for frontend.

I've done that, created a copy of the template file (shortcode-pdf-light-viewer.php) placed that in my child-theme and uploaded it to the site. After I do that the page won't propagate correctly.  I can't see any page content, just empty pages.  When I check the console in Chrome Developer Tools I can see a bunch of errors... all missing files. (I can see my added `<!-- pdf-light-viewer customization -->` notes.  I didn't change anything else, first time through.)

    (index):250 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00001-100x76.jpg 404 (Not Found)
    (index):876 GET http://mywebsiterurl.com/wp-content/plugins/pdf-light-viewer/assets/bower_components/fontawesome/fonts/fontawesome-webfont.woff2?v=4.3.0 
    (index):261 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00003-100x76.jpg 404 (Not Found)
    (index):257 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00002-100x76.jpg 404 (Not Found)
    (index):268 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00004-100x76.jpg 404 (Not Found)
    (index):1 GET http://dempsey-demo.com/page-00001.jpg 404 (Not Found)
    (index):280 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00006-100x76.jpg 404 (Not Found)
    (index):272 GET http://mywebsiterurl.com/category/newsletter/-thumbs/page-00005-100x76.jpg 404 (Not Found)
    jquery.js?ver=1.11.2:3 GET http://mywebsiterurl.com/wp-content/plugins/pdf-light-viewer/assets/bower_components/bxslider-4/dist/images/bx_loader.gif 404 (Not Found)

The actual (correct) address to those files on my server is:
http://mywebsiterurl.com/wp-content/uploads/pdf-light-viewer/617/page-00001-100x76.jpg

Obviously something got missed in the template move / translation.  

When I go back to my child theme, rename the template file with a `DNU-` (Do Not Use) prefix, the site works fine.  I can see the individual page images.  Chrome DevTools shows: 

    <img class="js-pdf-light-viewer-lazy-loading" 
              src="http://mywebsiterurl.com/wp-content/uploads/pdf-light-viewer/617/page-00001.jpg" 
              data-original="http://mywebsiterurl.com/wp-content/uploads/pdf-light-viewer/617/page-00001.jpg" 
              width="100%" height="100%" style="display: inline;">

... which exactly matches my storage system.  The other addresses generated are just odd.  Not sure where that is coming from.

**Comment by antongorodezkiy** [comment]
@zipzit thank you for reporting
